[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[deploy.environmentVariables]]
name = "FLASK_ENV"
value = "production"

[[deploy.environmentVariables]]
name = "PYTHONUNBUFFERED"
value = "1"
